/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Disruption {
  'affectedShipmentIds' : Array<bigint>,
  'disruptionId' : bigint,
  'description' : string,
  'isActive' : boolean,
  'timestamp' : Time,
  'disruptionType' : DisruptionType,
  'severity' : Severity,
  'estimatedResolutionTime' : Time,
  'location' : string,
}
export type DisruptionType = { 'portCongestion' : null } |
  { 'weatherAdvisory' : null } |
  { 'customsDelay' : null } |
  { 'operationalBottleneck' : null } |
  { 'infrastructureFailure' : null };
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export interface RouteOptimization {
  'status' : Status__1,
  'suggestedRoute' : string,
  'optimizationId' : bigint,
  'currentDelay' : Time,
  'currentRoute' : string,
  'createdAt' : Time,
  'estimatedSavings' : bigint,
  'shipmentId' : bigint,
  'reason' : string,
}
export type Severity = { 'red' : null } |
  { 'orange' : null } |
  { 'yellow' : null };
export interface Shipment {
  'eta' : Time,
  'weight' : bigint,
  'status' : Status,
  'destination' : string,
  'value' : bigint,
  'origin' : string,
  'lastUpdated' : Time,
  'routeId' : bigint,
  'currentLocation' : string,
  'shipmentId' : bigint,
  'carrier' : string,
  'riskLevel' : RiskLevel,
}
export type Status = { 'atCustoms' : null } |
  { 'delayed' : null } |
  { 'arrivingSoon' : null } |
  { 'inTransit' : null } |
  { 'delivered' : null };
export type Status__1 = { 'pending' : null } |
  { 'applied' : null } |
  { 'rejected' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
  'department' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDisruption' : ActorMethod<[Disruption], bigint>,
  'addShipment' : ActorMethod<[Shipment], bigint>,
  'applyRouteOptimization' : ActorMethod<[bigint, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllDisruptions' : ActorMethod<[boolean], Array<Disruption>>,
  'getAllDisruptionsStatic' : ActorMethod<[], Array<Disruption>>,
  'getAllRouteOptimizationsStatic' : ActorMethod<[], Array<RouteOptimization>>,
  'getAllShipments' : ActorMethod<[[] | [Status]], Array<Shipment>>,
  'getAllShipmentsStatic' : ActorMethod<[], Array<Shipment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getKPIMetrics' : ActorMethod<
    [],
    {
      'totalActiveShipments' : bigint,
      'onTimeDeliveryRate' : bigint,
      'shipmentsAtRiskCount' : bigint,
      'activeDisruptionsCount' : bigint,
    }
  >,
  'getRouteOptimizations' : ActorMethod<
    [[] | [bigint]],
    Array<RouteOptimization>
  >,
  'getShipmentById' : ActorMethod<[bigint], [] | [Shipment]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resolveDisruption' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'triggerRouteOptimization' : ActorMethod<[RouteOptimization], bigint>,
  'updateShipment' : ActorMethod<[bigint, Status, RiskLevel], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];