/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const DisruptionType = IDL.Variant({
  'portCongestion' : IDL.Null,
  'weatherAdvisory' : IDL.Null,
  'customsDelay' : IDL.Null,
  'operationalBottleneck' : IDL.Null,
  'infrastructureFailure' : IDL.Null,
});
export const Severity = IDL.Variant({
  'red' : IDL.Null,
  'orange' : IDL.Null,
  'yellow' : IDL.Null,
});
export const Disruption = IDL.Record({
  'affectedShipmentIds' : IDL.Vec(IDL.Nat),
  'disruptionId' : IDL.Nat,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'timestamp' : Time,
  'disruptionType' : DisruptionType,
  'severity' : Severity,
  'estimatedResolutionTime' : Time,
  'location' : IDL.Text,
});
export const Status = IDL.Variant({
  'atCustoms' : IDL.Null,
  'delayed' : IDL.Null,
  'arrivingSoon' : IDL.Null,
  'inTransit' : IDL.Null,
  'delivered' : IDL.Null,
});
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const Shipment = IDL.Record({
  'eta' : Time,
  'weight' : IDL.Nat,
  'status' : Status,
  'destination' : IDL.Text,
  'value' : IDL.Nat,
  'origin' : IDL.Text,
  'lastUpdated' : Time,
  'routeId' : IDL.Nat,
  'currentLocation' : IDL.Text,
  'shipmentId' : IDL.Nat,
  'carrier' : IDL.Text,
  'riskLevel' : RiskLevel,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status__1 = IDL.Variant({
  'pending' : IDL.Null,
  'applied' : IDL.Null,
  'rejected' : IDL.Null,
});
export const RouteOptimization = IDL.Record({
  'status' : Status__1,
  'suggestedRoute' : IDL.Text,
  'optimizationId' : IDL.Nat,
  'currentDelay' : Time,
  'currentRoute' : IDL.Text,
  'createdAt' : Time,
  'estimatedSavings' : IDL.Nat,
  'shipmentId' : IDL.Nat,
  'reason' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'department' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDisruption' : IDL.Func([Disruption], [IDL.Nat], []),
  'addShipment' : IDL.Func([Shipment], [IDL.Nat], []),
  'applyRouteOptimization' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllDisruptions' : IDL.Func([IDL.Bool], [IDL.Vec(Disruption)], ['query']),
  'getAllDisruptionsStatic' : IDL.Func([], [IDL.Vec(Disruption)], ['query']),
  'getAllRouteOptimizationsStatic' : IDL.Func(
      [],
      [IDL.Vec(RouteOptimization)],
      ['query'],
    ),
  'getAllShipments' : IDL.Func(
      [IDL.Opt(Status)],
      [IDL.Vec(Shipment)],
      ['query'],
    ),
  'getAllShipmentsStatic' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getKPIMetrics' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalActiveShipments' : IDL.Nat,
          'onTimeDeliveryRate' : IDL.Nat,
          'shipmentsAtRiskCount' : IDL.Nat,
          'activeDisruptionsCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getRouteOptimizations' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Vec(RouteOptimization)],
      ['query'],
    ),
  'getShipmentById' : IDL.Func([IDL.Nat], [IDL.Opt(Shipment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resolveDisruption' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'triggerRouteOptimization' : IDL.Func([RouteOptimization], [IDL.Nat], []),
  'updateShipment' : IDL.Func([IDL.Nat, Status, RiskLevel], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const DisruptionType = IDL.Variant({
    'portCongestion' : IDL.Null,
    'weatherAdvisory' : IDL.Null,
    'customsDelay' : IDL.Null,
    'operationalBottleneck' : IDL.Null,
    'infrastructureFailure' : IDL.Null,
  });
  const Severity = IDL.Variant({
    'red' : IDL.Null,
    'orange' : IDL.Null,
    'yellow' : IDL.Null,
  });
  const Disruption = IDL.Record({
    'affectedShipmentIds' : IDL.Vec(IDL.Nat),
    'disruptionId' : IDL.Nat,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'timestamp' : Time,
    'disruptionType' : DisruptionType,
    'severity' : Severity,
    'estimatedResolutionTime' : Time,
    'location' : IDL.Text,
  });
  const Status = IDL.Variant({
    'atCustoms' : IDL.Null,
    'delayed' : IDL.Null,
    'arrivingSoon' : IDL.Null,
    'inTransit' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Shipment = IDL.Record({
    'eta' : Time,
    'weight' : IDL.Nat,
    'status' : Status,
    'destination' : IDL.Text,
    'value' : IDL.Nat,
    'origin' : IDL.Text,
    'lastUpdated' : Time,
    'routeId' : IDL.Nat,
    'currentLocation' : IDL.Text,
    'shipmentId' : IDL.Nat,
    'carrier' : IDL.Text,
    'riskLevel' : RiskLevel,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status__1 = IDL.Variant({
    'pending' : IDL.Null,
    'applied' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const RouteOptimization = IDL.Record({
    'status' : Status__1,
    'suggestedRoute' : IDL.Text,
    'optimizationId' : IDL.Nat,
    'currentDelay' : Time,
    'currentRoute' : IDL.Text,
    'createdAt' : Time,
    'estimatedSavings' : IDL.Nat,
    'shipmentId' : IDL.Nat,
    'reason' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'department' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDisruption' : IDL.Func([Disruption], [IDL.Nat], []),
    'addShipment' : IDL.Func([Shipment], [IDL.Nat], []),
    'applyRouteOptimization' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllDisruptions' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(Disruption)],
        ['query'],
      ),
    'getAllDisruptionsStatic' : IDL.Func([], [IDL.Vec(Disruption)], ['query']),
    'getAllRouteOptimizationsStatic' : IDL.Func(
        [],
        [IDL.Vec(RouteOptimization)],
        ['query'],
      ),
    'getAllShipments' : IDL.Func(
        [IDL.Opt(Status)],
        [IDL.Vec(Shipment)],
        ['query'],
      ),
    'getAllShipmentsStatic' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getKPIMetrics' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalActiveShipments' : IDL.Nat,
            'onTimeDeliveryRate' : IDL.Nat,
            'shipmentsAtRiskCount' : IDL.Nat,
            'activeDisruptionsCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getRouteOptimizations' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(RouteOptimization)],
        ['query'],
      ),
    'getShipmentById' : IDL.Func([IDL.Nat], [IDL.Opt(Shipment)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resolveDisruption' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'triggerRouteOptimization' : IDL.Func([RouteOptimization], [IDL.Nat], []),
    'updateShipment' : IDL.Func([IDL.Nat, Status, RiskLevel], [], []),
  });
};

export const init = ({ IDL }) => { return []; };