/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface RouteOptimization {
    status: Status__1;
    suggestedRoute: string;
    optimizationId: bigint;
    currentDelay: Time;
    currentRoute: string;
    createdAt: Time;
    estimatedSavings: bigint;
    shipmentId: bigint;
    reason: string;
}
export interface Shipment {
    eta: Time;
    weight: bigint;
    status: Status;
    destination: string;
    value: bigint;
    origin: string;
    lastUpdated: Time;
    routeId: bigint;
    currentLocation: string;
    shipmentId: bigint;
    carrier: string;
    riskLevel: RiskLevel;
}
export interface Disruption {
    affectedShipmentIds: Array<bigint>;
    disruptionId: bigint;
    description: string;
    isActive: boolean;
    timestamp: Time;
    disruptionType: DisruptionType;
    severity: Severity;
    estimatedResolutionTime: Time;
    location: string;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
    department: string;
}
export enum DisruptionType {
    portCongestion = "portCongestion",
    weatherAdvisory = "weatherAdvisory",
    customsDelay = "customsDelay",
    operationalBottleneck = "operationalBottleneck",
    infrastructureFailure = "infrastructureFailure"
}
export enum RiskLevel {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export enum Severity {
    red = "red",
    orange = "orange",
    yellow = "yellow"
}
export enum Status {
    atCustoms = "atCustoms",
    delayed = "delayed",
    arrivingSoon = "arrivingSoon",
    inTransit = "inTransit",
    delivered = "delivered"
}
export enum Status__1 {
    pending = "pending",
    applied = "applied",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDisruption(disruption: Disruption): Promise<bigint>;
    addShipment(shipment: Shipment): Promise<bigint>;
    applyRouteOptimization(id: bigint, approved: boolean): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllDisruptions(activeOnly: boolean): Promise<Array<Disruption>>;
    getAllDisruptionsStatic(): Promise<Array<Disruption>>;
    getAllRouteOptimizationsStatic(): Promise<Array<RouteOptimization>>;
    getAllShipments(statusFilter: Status | null): Promise<Array<Shipment>>;
    getAllShipmentsStatic(): Promise<Array<Shipment>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getKPIMetrics(): Promise<{
        totalActiveShipments: bigint;
        onTimeDeliveryRate: bigint;
        shipmentsAtRiskCount: bigint;
        activeDisruptionsCount: bigint;
    }>;
    getRouteOptimizations(shipmentId: bigint | null): Promise<Array<RouteOptimization>>;
    getShipmentById(id: bigint): Promise<Shipment | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    resolveDisruption(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    triggerRouteOptimization(optimization: RouteOptimization): Promise<bigint>;
    updateShipment(id: bigint, newStatus: Status, newRiskLevel: RiskLevel): Promise<void>;
}
import type { Disruption as _Disruption, DisruptionType as _DisruptionType, RiskLevel as _RiskLevel, RouteOptimization as _RouteOptimization, Severity as _Severity, Shipment as _Shipment, Status as _Status, Status__1 as _Status__1, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDisruption(arg0: Disruption): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDisruption(to_candid_Disruption_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDisruption(to_candid_Disruption_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addShipment(arg0: Shipment): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addShipment(to_candid_Shipment_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShipment(to_candid_Shipment_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async applyRouteOptimization(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyRouteOptimization(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyRouteOptimization(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllDisruptions(arg0: boolean): Promise<Array<Disruption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDisruptions(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDisruptions(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDisruptionsStatic(): Promise<Array<Disruption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDisruptionsStatic();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDisruptionsStatic();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRouteOptimizationsStatic(): Promise<Array<RouteOptimization>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRouteOptimizationsStatic();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRouteOptimizationsStatic();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllShipments(arg0: Status | null): Promise<Array<Shipment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShipments(to_candid_opt_n27(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShipments(to_candid_opt_n27(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllShipmentsStatic(): Promise<Array<Shipment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShipmentsStatic();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShipmentsStatic();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKPIMetrics(): Promise<{
        totalActiveShipments: bigint;
        onTimeDeliveryRate: bigint;
        shipmentsAtRiskCount: bigint;
        activeDisruptionsCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getKPIMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKPIMetrics();
            return result;
        }
    }
    async getRouteOptimizations(arg0: bigint | null): Promise<Array<RouteOptimization>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRouteOptimizations(to_candid_opt_n38(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRouteOptimizations(to_candid_opt_n38(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShipmentById(arg0: bigint): Promise<Shipment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShipmentById(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShipmentById(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async resolveDisruption(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveDisruption(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveDisruption(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async triggerRouteOptimization(arg0: RouteOptimization): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.triggerRouteOptimization(to_candid_RouteOptimization_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.triggerRouteOptimization(to_candid_RouteOptimization_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateShipment(arg0: bigint, arg1: Status, arg2: RiskLevel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShipment(arg0, to_candid_Status_n9(this._uploadFile, this._downloadFile, arg1), to_candid_RiskLevel_n11(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShipment(arg0, to_candid_Status_n9(this._uploadFile, this._downloadFile, arg1), to_candid_RiskLevel_n11(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_DisruptionType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DisruptionType): DisruptionType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Disruption_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Disruption): Disruption {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_RouteOptimization_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RouteOptimization): RouteOptimization {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Severity_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Severity): Severity {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Shipment_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Shipment): Shipment {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Status__1_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status__1): Status__1 {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Shipment]): Shipment | null {
    return value.length === 0 ? null : from_candid_Shipment_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    affectedShipmentIds: Array<bigint>;
    disruptionId: bigint;
    description: string;
    isActive: boolean;
    timestamp: _Time;
    disruptionType: _DisruptionType;
    severity: _Severity;
    estimatedResolutionTime: _Time;
    location: string;
}): {
    affectedShipmentIds: Array<bigint>;
    disruptionId: bigint;
    description: string;
    isActive: boolean;
    timestamp: Time;
    disruptionType: DisruptionType;
    severity: Severity;
    estimatedResolutionTime: Time;
    location: string;
} {
    return {
        affectedShipmentIds: value.affectedShipmentIds,
        disruptionId: value.disruptionId,
        description: value.description,
        isActive: value.isActive,
        timestamp: value.timestamp,
        disruptionType: from_candid_DisruptionType_n18(_uploadFile, _downloadFile, value.disruptionType),
        severity: from_candid_Severity_n20(_uploadFile, _downloadFile, value.severity),
        estimatedResolutionTime: value.estimatedResolutionTime,
        location: value.location
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _Status__1;
    suggestedRoute: string;
    optimizationId: bigint;
    currentDelay: _Time;
    currentRoute: string;
    createdAt: _Time;
    estimatedSavings: bigint;
    shipmentId: bigint;
    reason: string;
}): {
    status: Status__1;
    suggestedRoute: string;
    optimizationId: bigint;
    currentDelay: Time;
    currentRoute: string;
    createdAt: Time;
    estimatedSavings: bigint;
    shipmentId: bigint;
    reason: string;
} {
    return {
        status: from_candid_Status__1_n25(_uploadFile, _downloadFile, value.status),
        suggestedRoute: value.suggestedRoute,
        optimizationId: value.optimizationId,
        currentDelay: value.currentDelay,
        currentRoute: value.currentRoute,
        createdAt: value.createdAt,
        estimatedSavings: value.estimatedSavings,
        shipmentId: value.shipmentId,
        reason: value.reason
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eta: _Time;
    weight: bigint;
    status: _Status;
    destination: string;
    value: bigint;
    origin: string;
    lastUpdated: _Time;
    routeId: bigint;
    currentLocation: string;
    shipmentId: bigint;
    carrier: string;
    riskLevel: _RiskLevel;
}): {
    eta: Time;
    weight: bigint;
    status: Status;
    destination: string;
    value: bigint;
    origin: string;
    lastUpdated: Time;
    routeId: bigint;
    currentLocation: string;
    shipmentId: bigint;
    carrier: string;
    riskLevel: RiskLevel;
} {
    return {
        eta: value.eta,
        weight: value.weight,
        status: from_candid_Status_n31(_uploadFile, _downloadFile, value.status),
        destination: value.destination,
        value: value.value,
        origin: value.origin,
        lastUpdated: value.lastUpdated,
        routeId: value.routeId,
        currentLocation: value.currentLocation,
        shipmentId: value.shipmentId,
        carrier: value.carrier,
        riskLevel: from_candid_RiskLevel_n33(_uploadFile, _downloadFile, value.riskLevel)
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    portCongestion: null;
} | {
    weatherAdvisory: null;
} | {
    customsDelay: null;
} | {
    operationalBottleneck: null;
} | {
    infrastructureFailure: null;
}): DisruptionType {
    return "portCongestion" in value ? DisruptionType.portCongestion : "weatherAdvisory" in value ? DisruptionType.weatherAdvisory : "customsDelay" in value ? DisruptionType.customsDelay : "operationalBottleneck" in value ? DisruptionType.operationalBottleneck : "infrastructureFailure" in value ? DisruptionType.infrastructureFailure : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    orange: null;
} | {
    yellow: null;
}): Severity {
    return "red" in value ? Severity.red : "orange" in value ? Severity.orange : "yellow" in value ? Severity.yellow : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    applied: null;
} | {
    rejected: null;
}): Status__1 {
    return "pending" in value ? Status__1.pending : "applied" in value ? Status__1.applied : "rejected" in value ? Status__1.rejected : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    atCustoms: null;
} | {
    delayed: null;
} | {
    arrivingSoon: null;
} | {
    inTransit: null;
} | {
    delivered: null;
}): Status {
    return "atCustoms" in value ? Status.atCustoms : "delayed" in value ? Status.delayed : "arrivingSoon" in value ? Status.arrivingSoon : "inTransit" in value ? Status.inTransit : "delivered" in value ? Status.delivered : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): RiskLevel {
    return "low" in value ? RiskLevel.low : "high" in value ? RiskLevel.high : "critical" in value ? RiskLevel.critical : "medium" in value ? RiskLevel.medium : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Disruption>): Array<Disruption> {
    return value.map((x)=>from_candid_Disruption_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RouteOptimization>): Array<RouteOptimization> {
    return value.map((x)=>from_candid_RouteOptimization_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Shipment>): Array<Shipment> {
    return value.map((x)=>from_candid_Shipment_n29(_uploadFile, _downloadFile, x));
}
function to_candid_DisruptionType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DisruptionType): _DisruptionType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Disruption_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Disruption): _Disruption {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_RiskLevel_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): _RiskLevel {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_RouteOptimization_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RouteOptimization): _RouteOptimization {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_Severity_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): _Severity {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Shipment_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Shipment): _Shipment {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Status__1_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): _Status__1 {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status | null): [] | [_Status] {
    return value === null ? candid_none() : candid_some(to_candid_Status_n9(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    affectedShipmentIds: Array<bigint>;
    disruptionId: bigint;
    description: string;
    isActive: boolean;
    timestamp: Time;
    disruptionType: DisruptionType;
    severity: Severity;
    estimatedResolutionTime: Time;
    location: string;
}): {
    affectedShipmentIds: Array<bigint>;
    disruptionId: bigint;
    description: string;
    isActive: boolean;
    timestamp: _Time;
    disruptionType: _DisruptionType;
    severity: _Severity;
    estimatedResolutionTime: _Time;
    location: string;
} {
    return {
        affectedShipmentIds: value.affectedShipmentIds,
        disruptionId: value.disruptionId,
        description: value.description,
        isActive: value.isActive,
        timestamp: value.timestamp,
        disruptionType: to_candid_DisruptionType_n3(_uploadFile, _downloadFile, value.disruptionType),
        severity: to_candid_Severity_n5(_uploadFile, _downloadFile, value.severity),
        estimatedResolutionTime: value.estimatedResolutionTime,
        location: value.location
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Status__1;
    suggestedRoute: string;
    optimizationId: bigint;
    currentDelay: Time;
    currentRoute: string;
    createdAt: Time;
    estimatedSavings: bigint;
    shipmentId: bigint;
    reason: string;
}): {
    status: _Status__1;
    suggestedRoute: string;
    optimizationId: bigint;
    currentDelay: _Time;
    currentRoute: string;
    createdAt: _Time;
    estimatedSavings: bigint;
    shipmentId: bigint;
    reason: string;
} {
    return {
        status: to_candid_Status__1_n42(_uploadFile, _downloadFile, value.status),
        suggestedRoute: value.suggestedRoute,
        optimizationId: value.optimizationId,
        currentDelay: value.currentDelay,
        currentRoute: value.currentRoute,
        createdAt: value.createdAt,
        estimatedSavings: value.estimatedSavings,
        shipmentId: value.shipmentId,
        reason: value.reason
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eta: Time;
    weight: bigint;
    status: Status;
    destination: string;
    value: bigint;
    origin: string;
    lastUpdated: Time;
    routeId: bigint;
    currentLocation: string;
    shipmentId: bigint;
    carrier: string;
    riskLevel: RiskLevel;
}): {
    eta: _Time;
    weight: bigint;
    status: _Status;
    destination: string;
    value: bigint;
    origin: string;
    lastUpdated: _Time;
    routeId: bigint;
    currentLocation: string;
    shipmentId: bigint;
    carrier: string;
    riskLevel: _RiskLevel;
} {
    return {
        eta: value.eta,
        weight: value.weight,
        status: to_candid_Status_n9(_uploadFile, _downloadFile, value.status),
        destination: value.destination,
        value: value.value,
        origin: value.origin,
        lastUpdated: value.lastUpdated,
        routeId: value.routeId,
        currentLocation: value.currentLocation,
        shipmentId: value.shipmentId,
        carrier: value.carrier,
        riskLevel: to_candid_RiskLevel_n11(_uploadFile, _downloadFile, value.riskLevel)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    atCustoms: null;
} | {
    delayed: null;
} | {
    arrivingSoon: null;
} | {
    inTransit: null;
} | {
    delivered: null;
} {
    return value == Status.atCustoms ? {
        atCustoms: null
    } : value == Status.delayed ? {
        delayed: null
    } : value == Status.arrivingSoon ? {
        arrivingSoon: null
    } : value == Status.inTransit ? {
        inTransit: null
    } : value == Status.delivered ? {
        delivered: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
} {
    return value == RiskLevel.low ? {
        low: null
    } : value == RiskLevel.high ? {
        high: null
    } : value == RiskLevel.critical ? {
        critical: null
    } : value == RiskLevel.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DisruptionType): {
    portCongestion: null;
} | {
    weatherAdvisory: null;
} | {
    customsDelay: null;
} | {
    operationalBottleneck: null;
} | {
    infrastructureFailure: null;
} {
    return value == DisruptionType.portCongestion ? {
        portCongestion: null
    } : value == DisruptionType.weatherAdvisory ? {
        weatherAdvisory: null
    } : value == DisruptionType.customsDelay ? {
        customsDelay: null
    } : value == DisruptionType.operationalBottleneck ? {
        operationalBottleneck: null
    } : value == DisruptionType.infrastructureFailure ? {
        infrastructureFailure: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): {
    pending: null;
} | {
    applied: null;
} | {
    rejected: null;
} {
    return value == Status__1.pending ? {
        pending: null
    } : value == Status__1.applied ? {
        applied: null
    } : value == Status__1.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): {
    red: null;
} | {
    orange: null;
} | {
    yellow: null;
} {
    return value == Severity.red ? {
        red: null
    } : value == Severity.orange ? {
        orange: null
    } : value == Severity.yellow ? {
        yellow: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
